### ISSUE TITLE
Groupdocs Full text search

### ISSUE THREAD

**Issue by SriAzureDev** [groupdocs-free-consulting/display-document-in-browser-without-downloading#2]
Hi,

 it would be helpful if you can provide me clarification on the below.

I have a requirement that my documents are stored in SQL server and I would like to implement full-text search requirement, suppose - When I enter sample to search, it should go to SQL server and get me all the document names having “sample” in their file name and next it should search for all the file content having a sample. Finally, it should return the files in the order of having “Sample” in large count first followed by subsequent files.

Please let me know if this is possible with Groupdocs, if so please share with me some samples to work with.

Thank you in advance.

**Comment by atirtahirgroupdocs** [comment]
@SriAzureDev 
We already answered this query on [forum](https://forum.groupdocs.com/t/search-view-merge-download-navigate-add-comments-print-options/9043/5?u=atir_tahir).
